CREATE TABLE gyms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    plan VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE class_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    duration_min INT NOT NULL,
    default_capacity INT NOT NULL,
    CONSTRAINT fk_class_types_gym
        FOREIGN KEY (gym_id) REFERENCES gyms(id)
        ON DELETE RESTRICT,
    CONSTRAINT uk_class_types_gym_name UNIQUE (gym_id, name)
);
